var Librairie_Textures = [
    
    "Images/Chat.png",
    "Images/IconSet.png",

    "Images/CasseBrique/Background.png",
    "Images/CasseBrique/Balle.png",
    "Images/CasseBrique/Brique1.png",
    "Images/CasseBrique/Brique2.png",
    "Images/CasseBrique/Brique3.png",
    "Images/CasseBrique/Brique4.png",
    "Images/CasseBrique/Brique5.png",
    "Images/CasseBrique/Paddle.png",

    "Images/Joueur/B_0.png",
    "Images/Joueur/B_1.png",
    "Images/Joueur/B_2.png",
    "Images/Joueur/D_0.png",
    "Images/Joueur/D_1.png",
    "Images/Joueur/D_2.png",
    "Images/Joueur/G_0.png",
    "Images/Joueur/G_1.png",
    "Images/Joueur/G_2.png",
    "Images/Joueur/H_0.png",
    "Images/Joueur/H_1.png",
    "Images/Joueur/H_2.png",
    "Images/Joueur/Perso.png",
    "Images/Joueur/Perso2.png",

    "Images/Moto/Moto1.png",
    "Images/Moto/Moto2.png",
    "Images/Moto/Route.jpg",
    "Images/Moto/Voiture1.png",
    "Images/Moto/Voiture2.png",
    "Images/Moto/Voiture3.png",
    "Images/Moto/Voiture4.png",
    "Images/Moto/Roue.png",
    "Images/Moto/Compteur.png",
    "Images/Moto/Aiguille.png",
    "Images/Moto/FlammeAnimation.png",
    "Images/Moto/Score.png",
    "Images/Moto/Multiplicateur.png",

    "Images/Tilemap/A1_Eau1.png",
    "Images/Tilemap/A1_Eau2.png",
    // "Images/Tilemap/A1_Eau3.png",
    // "Images/Tilemap/A2_Extérieur1.png",
    "Images/Tilemap/A2_Extérieur2.png",
    // "Images/Tilemap/A2_Extérieur3.png",
    // "Images/Tilemap/A3_Mur1.png",
    // "Images/Tilemap/A3_Mur2.png",
    "Images/Tilemap/A3_Mur3.png",
    // "Images/Tilemap/A4_Mur1.png",
    // "Images/Tilemap/A4_Mur2.png",
    "Images/Tilemap/A4_Mur3.png",
    // "Images/Tilemap/A4_Mur4.png",
    // "Images/Tilemap/A5_Bateau1.png",
    // "Images/Tilemap/A5_Bateau2.png",
    // "Images/Tilemap/A5_Donjon1.png",
    // "Images/Tilemap/A5_Donjon2.png",
    // "Images/Tilemap/A5_Donjon3.png",
    "Images/Tilemap/A5_Donjon4.png",
    // "Images/Tilemap/A5_Extérieur1.png",
    // "Images/Tilemap/A5_Extérieur2.png",
    // "Images/Tilemap/A5_Extérieur3.png",
    // "Images/Tilemap/A5_Extérieur4.png",
    // "Images/Tilemap/A5_Extérieur5.png",
    "Images/Tilemap/A5_Extérieur6.png",
    // "Images/Tilemap/A5_Extérieur7.png",
    "Images/Tilemap/A5_Extérieur8.png",
    // "Images/Tilemap/A5_Extérieur9.png",
    // "Images/Tilemap/A5_Extérieur10.png",
    // "Images/Tilemap/A5_Extérieur11.png",
    "Images/Tilemap/A5_Extérieur12.png",
    // "Images/Tilemap/A5_Extérieur13.png",
    // "Images/Tilemap/A5_Extérieur14.png",
    // "Images/Tilemap/A5_Intérieur1.png",
    // "Images/Tilemap/A5_Intérieur2.png",
    // "Images/Tilemap/A5_Intérieur3.png",
    // "Images/Tilemap/A5_Intérieur4.png",
    // "Images/Tilemap/A5_Intérieur5.png",
    // "Images/Tilemap/A5_Intérieur6.png",
    // "Images/Tilemap/A5_Intérieur7.png",
    // "Images/Tilemap/A5_Intérieur8.png",
    "Images/Tilemap/A5_Intérieur9.png",
    // "Images/Tilemap/A5_Intérieur10.png",
    // "Images/Tilemap/A5_Toit1.png",
    // "Images/Tilemap/A5_Toit2.png",
    // "Images/Tilemap/A5_Toit3.png",
    // "Images/Tilemap/A5_Toit4.png",
    // "Images/Tilemap/Water.png",
]